{"uuid": "b29c659c-992a-44e1-90a8-9195a02aff8c", "rulebook_name": "lol", "description": "Regulatory framework for lol", "file_path": "/app/code/src/data/rulebooks/b29c659c-992a-44e1-90a8-9195a02aff8c/FR_Y-14Q20240331_i-160-218.pdf", "created_at": "2025-03-25T15:05:49.450035", "file_size": 698336, "original_filename": "FR_Y-14Q20240331_i-160-218.pdf", "status": "FAILED", "rules": [], "processing_error": "Error generating rules: Task <Task pending name='Task-7' coro=<RulebookService.create_rulebook() running at /app/code/src/backend/app/services/rulebook_service.py:141> cb=[_run_until_complete_cb() at /usr/local/lib/python3.11/asyncio/base_events.py:181]> got Future <Task pending name='Task-8' coro=<UnaryUnaryCall._invoke() running at /usr/local/lib/python3.11/site-packages/grpc/aio/_call.py:577>> attached to a different loop"}